### ISSUE TITLE
建议：分发插件事件，在玩家上线时派发其玩家名和IP地址

### ISSUE THREAD

**Issue by Mooling0602** [LoosePrince/PF-player_ip_logger#2]
这样可以方便在玩家上线时进行处理，实现广播其IP归属地等操作。
参考：https://mcdreforged.com/zh-CN/plugin/iploc

**Comment by Mooling0602** [comment]
参考文档：https://docs.mcdreforged.com/zh-cn/latest/code_references/ServerInterface.html#mcdreforged.plugin.si.server_interface.ServerInterface.dispatch_event:~:text=ServerInterface.dispatch_event()

**Comment by XueK66** [comment]
好嘟，马上写
事件名称: `player_ip_logger.player_login`
传入变量: (`player_name`:str, `player_ip`:str)
触发条件: 
- 非机器人（IP不为`/local`）
- 非被封玩家 （通过本插件禁止的玩家或ip）

**Comment by XueK66** [comment]
已更新版本 `1.2.0` (#3)  详情请见上条回复。谢谢你的提议啦！

**Comment by Mooling0602** [comment]
感谢你的支持，我将在我插件的下个版本中尝试对接你的插件：https://mcdreforged.com/zh-CN/plugin/iploc

**Comment by Mooling0602** [comment]
> 已更新版本 `1.2.0` (#3) 详情请见上条回复。谢谢你的提议啦！

尝试对接了下，目前测试正常：https://mcdreforged.com/zh-CN/plugin/iploc/release/0.1.0
